services:
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend.Dockerfile
  #   ports:
  #     - "4200:80"
  #   depends_on:
  #     - backend

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: mysql://admin:admin@1234@db:3306/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin@1234
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin --user=$${MYSQL_USER} --password=$${MYSQL_PASSWORD} --host=localhost ping",
        ]
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin@1234
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
