nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https?:\/\/localhost(:[0-9]+)?$']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS', 'PATCH']
        allow_headers: ['*']
        expose_headers: ['Link']
        allow_credentials: true
        max_age: 3600
    paths:
        '^/': null
