import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { Room } from '../models/room.model'; // Import Room model

@Injectable({
  providedIn: 'root'
})
export class RoomService {
  private apiUrl = 'http://localhost:8000/api/rooms';

  constructor(private http: HttpClient) {}

  // GET /api/rooms - Public
  getRooms(): Observable<Room[]> {
    return this.http.get<Room[]>(this.apiUrl).pipe(
      catchError(this.handleError)
    );
  }

  // GET /api/rooms/{id} - Public (or Authenticated?)
  getRoom(id: number): Observable<Room> {
    return this.http.get<Room>(`${this.apiUrl}/${id}`).pipe(
      catchError(this.handleError)
    );
  }

  // POST /api/rooms - Employee/Admin only
  // Use Omit<Room, 'id'> for create DTO as id is generated by backend
  createRoom(roomData: Omit<Room, 'id'>): Observable<Room> {
    return this.http.post<Room>(this.apiUrl, roomData).pipe(
      catchError(this.handleError)
    );
  }

  // PATCH /api/rooms/{id} - Employee/Admin only
  // Use Partial<Room> for update DTO
  updateRoom(id: number, roomData: Partial<Room>): Observable<Room> {
    return this.http.patch<Room>(`${this.apiUrl}/${id}`, roomData).pipe(
      catchError(this.handleError)
    );
  }

  // DELETE /api/rooms/{id} - Employee/Admin only
  deleteRoom(id: number): Observable<void> {
    return this.http.delete<void>(`${this.apiUrl}/${id}`).pipe(
      catchError(this.handleError)
    );
  }

  // Basic error handling (could be centralized)
  private handleError(error: HttpErrorResponse) {
    let msg = 'An unknown error occurred!';
    if (error.error instanceof ErrorEvent) {
      msg = `Error: ${error.error.message}`;
    } else {
      msg = `Error Code: ${error.status}\nMessage: ${error.message}`;
      if (error.error && error.error.message) {
        msg = error.error.message;
      }
    }
    console.error(error);
    return throwError(() => new Error(msg));
  }
}